### ISSUE TITLE
Improve website and map integration on mobile phones

### ISSUE THREAD

**Issue by sylvainar** [WikiJourney/wikijourney_website#47]
**This issue is about discussing the new responsive design and its features**

This issue proposes new features for the responsive version, currently in development. Check [the sandbox](http://dev.wikijourney.eu/dev_design/).

Propose ameliorations below ! :wink: 

- [x] The logo in the navbar doesn't always shrink on map page
- [x] Popup are taking too much space
- [x] Popup should close when the map is moved
- [x] It could be interesting to have an animation on the cart icon for each POI added
- [x] The cart is too wide for big screens (Got it's own issue : #57)

~~The cart should appear on first POI added~~ _(not necessary if there is an animation)_
~~Propose a simplified version in case the mobile phone is too old for jQuery~~ (_solution given by tikiki below_)

EDIT 29/05 (@tikiki) :
- [x] Cart should not be open by default on mobile, and even should not open when the window is resized
- [x] The title is too wide between 528px and ~600px wide
- [x] Change the cart icon to something more understandable (like an arrow on the middle left of the screen, since the button used to close the drawer is an arrow)
- [x] Bigger text links on the popups
- [x] About the simplified version without jQuery: rewrite ~~everything~~ most without using jQuery in the first place

EDIT 06/06 (@pyguerder) : 
- [x] Delete link to jsonparse.js

EDIT 11/07 : 
- [x] Images can easily go out of popups if they're not in browser's cache.

**Comment by tikiki** [comment]
- [ ] Cart should not be open by default on mobile, and even should not open when the window is resized
- [ ] The title is too wide between 528px and ~600px wide
- [ ] Change the cart icon to something more understandable (like an arrow on the middle left of the screen, since the button used to close the drawer is an arrow)
- [ ] Bigger text links on the popups
- [ ] About the simplified version without jQuery: rewrite ~~everything~~ most without using jQuery in the first place

I disagree with "the cart should open on first POI added". If the animation is clear enough (eg. bouncing arrow), this should not be necessary.

**Comment by pyguerder** [comment]
Note: I see an Error 500 on jsonparse.js when I load the map:
![err500](https://cloud.githubusercontent.com/assets/6534215/15835887/66010d90-2c32-11e6-8e72-2025546ef7b9.png)

**Comment by sylvainar** [comment]
For the error 500, it's a script I tried but at the end of the day it wasn't necessary, so I deleted the script and forgot to remove the link, thanks for noticing.

For the guiding, it's normal : I've modified the routing machine from OSRM to Mapzen Turn By Turn, because it allows pedestrian routing, however it still a bit buggy, I've opened an issue on their Github. If it's not solved before the release, I will try something else or go back in auto mode until the next version.
